### ISSUE TITLE
Missing 'MacOS' sub-directory in 'execPath' for Mac builds

### ISSUE THREAD

**Issue by cstringer** [dusionlike/electron-builder-encryptor#11]
https://github.com/dusionlike/electron-builder-encryptor/blob/6bb97042619f78839d6e903b6c41544149a36d38/src/index.ts#L64

Currently, the executable path (`execPath`) for the `compileToBytenode()` function on MacOS builds is missing the "MacOS" subdirectory.  For example:
```
// current:
"./release/mac-arm64/electron-builder-encryptor-demo.app/Contents/electron-builder-encryptor-demo"

// required:
"./release/mac-arm64/electron-builder-encryptor-demo.app/Contents/MacOS/electron-builder-encryptor-demo"
```

And thank you for this cool project, it is a very interesting idea!

**Comment by dusionlike** [comment]
Sorry, I don't have a Mac, so I can't verify your issue.

**Comment by cstringer** [comment]
@dusionlike that's quite alright, I'm on a Mac and can easily verify this issue for you.

First, refer to Apple's documentation on the structure of a macOS `.app` bundle: https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1
```
MyApp.app/
   Contents/
      Info.plist
      MacOS/
      Resources/
```
As it mentions for the `MacOS` sub-directory: _"(Required) Contains the application’s standalone executable code. Typically, this directory contains only one binary file with your application’s main entry point and statically linked code."_

Here is the output from running `npm run release` on the "playground" code as-is:

![image](https://github.com/dusionlike/electron-builder-encryptor/assets/2779764/80a89dc1-b587-44f5-a8ab-c1f39279644c)

By adding the correct `MacOS` subdirectory in `index.ts`, the build succeeds:

![image](https://github.com/dusionlike/electron-builder-encryptor/assets/2779764/cc2032c5-8424-4770-8514-afbc13504ba2)
![image](https://github.com/dusionlike/electron-builder-encryptor/assets/2779764/f9091de1-a9dd-4e41-84da-91e7bb0a27c1)

Let me know if there's anything else I can provide to assist, thanks!

**Comment by dusionlike** [comment]
@cstringer It looks like you're right. Can you create a PR? thanks! ❤️
